version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - python/test:
          args: '--version'
          pkg-manager: pipenv
          test-tool: pytest
workflows:
  main:
    jobs:
      - build-and-test
